- name: Build CICD node
  hosts: "{{ servers }}"
  become: Yes
  become_user: root

  tasks:
  vars:
    jenkins_hostname: cicd
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      become: true