---
- name: Build Jenkins
  hosts: all
  vars:
    jenkins_hostname: 192.168.100.102
    jenkins_home: /vagrant/jenkins
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
      become: true